### ISSUE TITLE
Failed to download module

### ISSUE THREAD

**Issue by ahmedig** [Azure/terraform-azurerm-vnetpeering#6]
Hello,

I tried using the module, but I got this message:

Error: Failed to download module

Could not download module "vnetpeering" (networks.tf:31) source code from
"https://github.com/Azure/terraform-azurerm-vnetpeering/archive/v1.0.0.tar.gz//*?archive=tar.gz":
bad response code: 404.

Terraform version: 0.12.24

Thats the code that I used:
```
module "vnetpeering" {
  source               = "Azure/vnetpeering/azurerm"
  vnet_peering_names   = ["vnetpeering1", "vnetpeering2"]
  vnet_names           = [module.network_primary.vnet_name, module.network_secondary.vnet_name]
  resource_group_names = [azurerm_resource_group.networks.name, azurerm_resource_group.networks.name]

  tags = merge(local.common_tags, local.network_tags)
}
```

**Comment by arnemorten** [comment]
I'm seeing the same behavior on Terraform v0.13.0.

**Comment by katomel4** [comment]
error download on terraform 0.13.0

Could not download module "vnetpeering" (main.tf:68) source code from
"git::https://github.com/Azure/terraform-azurerm-vnetpeering?ref=v1.0.0":
error downloading
'https://github.com/Azure/terraform-azurerm-vnetpeering?ref=v1.0.0':
C:\Program Files\Git\mingw64\bin\git.exe exited with 1: error: pathspec
'v1.0.0' did not match any file(s) known to git
.

I will try clone it localy

**Comment by thefunny1983** [comment]
Having this exact same problem from my Gitlab Runner. Is there any way to fix this, apart from a local clone?

**Comment by walliski** [comment]
Also seeing the same issue.

**Comment by oulman** [comment]
@VaijanathB I believe the problem is that you're referencing v1.0.0 in the Terraform Registry and the only tag/release that exists in Github is for v1.0.

Can you create a tag for v1.0.0 or update the registry to use v1.0 so that we can pull the module?

Thanks!

**Comment by VaijanathB** [comment]
@grayzu Can you please take a look ?

**Comment by grayzu** [comment]
I have updated the tag to match the module so both are v1.0.0 and just tested to ensure the module downloads correctly when referenced in a configuration so this should be good to go.
